version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PW=crudjs      
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/volumes
      - /node_modules
    command: npm run start:dev

  postgres:
    image: postgres:alpine
    restart: always
    env_file: .env
    environment:
      - DB_USER=postgres
      - DB_PASS=crudjs

  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080