version: '3'

volume:
  test:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    env_file: .env 
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
     - type: volume
        source: test
        target: /data/api
    command: npm run start

  postgres:
    image: postgres:alpine
    restart: always
    env_file: .env

  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080
